# Generated by Django 5.0.7 on 2024-07-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='paid_until',
        ),
    ]
