# Generated by Django 5.0.7 on 2024-08-16 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestao', '0010_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopeeAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.integracao')),
            ],
        ),
    ]
