# Generated by Django 5.0.7 on 2024-08-19 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField()),
                ('session_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pendente', max_length=20)),
            ],
        ),
    ]
