# Generated by Django 5.0.7 on 2024-08-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopee', '0002_sessionintegration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopeeauth',
            name='integracao',
        ),
    ]
