# Generated by Django 5.0.7 on 2024-07-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_tenant_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
