# Generated by Django 5.0.7 on 2024-07-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_configuracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='valor',
            field=models.FloatField(),
        ),
    ]
