# Generated by Django 5.0.7 on 2024-07-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_configuracao_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='valor',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='custofixo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='embalagem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='imposto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='lucratividade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='publicidade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='transporte',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
