# Generated by Django 5.0.7 on 2024-07-25 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_remove_configuracao_nome_remove_configuracao_valor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuracao123',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imposto', models.FloatField(blank=True, null=True)),
                ('embalagem', models.FloatField(blank=True, null=True)),
                ('publicidade', models.FloatField(blank=True, null=True)),
                ('transporte', models.FloatField(blank=True, null=True)),
                ('custofixo', models.FloatField(blank=True, null=True)),
                ('lucratividade', models.FloatField(blank=True, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
