# Generated by Django 5.0.7 on 2024-07-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_configuracao123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='configuracao123',
        ),
    ]
