# Generated by Django 5.0.7 on 2024-08-09 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_delete_configuracao123'),
    ]

    operations = [
        migrations.CreateModel(
            name='integracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_src', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('is_activate', models.BooleanField(default=True)),
                ('id_marketplace', models.IntegerField()),
                ('id_seller', models.TextField()),
            ],
            options={
                'db_table': 'gestao_integracao',
            },
        ),
        migrations.CreateModel(
            name='MercadoLivreAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.integracao')),
            ],
        ),
    ]
