# Generated by Django 5.0.7 on 2024-08-09 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_integracao_mercadolivreauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_venda', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=200)),
                ('data_de_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comissao_taxa_fixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frete_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repasse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_anuncio', models.CharField(max_length=500)),
                ('titulo_anuncio', models.TextField()),
                ('sku', models.CharField(max_length=500)),
                ('quantidade', models.IntegerField()),
                ('modo_de_envio', models.CharField(max_length=200)),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.integracao')),
            ],
        ),
    ]
