# Generated by Django 5.0.7 on 2024-08-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLivreAnuncios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_anuncio', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('auth_code', models.CharField(default='default_auth_code_value', max_length=20)),
                ('titulo', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category_id', models.CharField(default='', max_length=20)),
                ('permalink', models.CharField(default='', max_length=500)),
                ('thumbnail', models.CharField(default='', max_length=500)),
                ('shipping_mode', models.TextField(default='')),
                ('shipping_free', models.BooleanField(default=True)),
                ('shipping_logistic_type', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='lucratividade',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='CMV',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='custofixo',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='embalagem',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='imposto',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='publicidade',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='transporte',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
