# Generated by Django 5.0.7 on 2024-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoLivreAnuncios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='lucratividade',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='CMV',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='custofixo',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='embalagem',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='imposto',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='publicidade',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='transporte',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
