# Generated by Django 5.0.7 on 2024-08-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_mercadolivreanuncios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadolivreanuncios',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
