# Generated by Django 5.0.7 on 2024-07-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_public', '0003_relatorio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='relatorio',
        ),
    ]
